/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canteen_register;

import canteen_connection.Connect;
import canteen_encrypt.EncryptSHA1;
import com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class registerAdmin extends javax.swing.JFrame {

    Connection conn;
    Statement st;
    
    /**
     * Creates new form registerAdmin
     */
    public registerAdmin() {
        initComponents();
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        labelIconRegister = new javax.swing.JLabel();
        labelTextfieldUsername = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        textFieldUsername = new javax.swing.JTextField();
        labelTextfieldPassword = new javax.swing.JLabel();
        textFieldPassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonRegister = new keeptoo.KButton();
        buttonCancel = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(153, 255, 51));
        kGradientPanel1.setkStartColor(new java.awt.Color(212, 247, 157));
        kGradientPanel1.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIconRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Male User_65px.png"))); // NOI18N
        jPanel1.add(labelIconRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 60, 60));

        labelTextfieldUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTextfieldUsername.setForeground(new java.awt.Color(102, 102, 102));
        labelTextfieldUsername.setText("Tài khoản");
        jPanel1.add(labelTextfieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 350, -1));

        textFieldUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textFieldUsername.setBorder(null);
        textFieldUsername.setOpaque(false);
        jPanel1.add(textFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 350, 30));

        labelTextfieldPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTextfieldPassword.setForeground(new java.awt.Color(102, 102, 102));
        labelTextfieldPassword.setText("Mật khẩu");
        jPanel1.add(labelTextfieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        textFieldPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textFieldPassword.setBorder(null);
        jPanel1.add(textFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 350, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 360, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Key_32px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/User_320px.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 30, 30));

        buttonRegister.setBorder(null);
        buttonRegister.setText("Đăng Kí");
        buttonRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonRegister.setkBackGroundColor(new java.awt.Color(0, 204, 102));
        buttonRegister.setkBorderRadius(50);
        buttonRegister.setkEndColor(new java.awt.Color(102, 255, 153));
        buttonRegister.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        buttonRegister.setkHoverStartColor(new java.awt.Color(0, 153, 102));
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(buttonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        buttonCancel.setBorder(null);
        buttonCancel.setText("Hủy");
        buttonCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonCancel.setkBackGroundColor(new java.awt.Color(0, 204, 102));
        buttonCancel.setkBorderRadius(50);
        buttonCancel.setkEndColor(new java.awt.Color(102, 255, 153));
        buttonCancel.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        buttonCancel.setkHoverStartColor(new java.awt.Color(0, 153, 102));
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        kGradientPanel1.add(jPanel1);
        jPanel1.setBounds(80, 80, 440, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        // TODO add your handling code here:
        String username = textFieldUsername.getText();
        
        try {
            String password = EncryptSHA1.sha1(textFieldPassword.getText());
        if (username.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(this, "Some field is empty", "Error", 1);
        } else {
                conn = Connect.getConnection();
                st = conn.createStatement();
                st.executeUpdate(String.format("insert into adminaccount (adminAccID, adminUserName, adminPassword) VALUES (NULL, '%s', '%s')", username, password));
                
                JOptionPane.showMessageDialog(this, "Admin account added successfully", "Success", 1);
                this.setVisible(false);
                
        }
        } catch (MySQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(this, "Username '"+username+"' is not available", "Error", 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 1);
            
        }
    }//GEN-LAST:event_buttonRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton buttonCancel;
    private keeptoo.KButton buttonRegister;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel labelIconRegister;
    private javax.swing.JLabel labelTextfieldPassword;
    private javax.swing.JLabel labelTextfieldUsername;
    private javax.swing.JPasswordField textFieldPassword;
    private javax.swing.JTextField textFieldUsername;
    // End of variables declaration//GEN-END:variables
}
