/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canteen_employees;

import canteen_connection.Connect;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class EmployeeManage extends javax.swing.JFrame {

    Employee employee;
    DefaultTableModel model;
    Connection conn;
    Statement st;
    ResultSet rs;
    /**
     * Creates new form NewJFrame
     */
    public EmployeeManage() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        showEmployeeInTable();
        
        
    }

    public ArrayList<Employee> getEmployeeList() {
        
            ArrayList<Employee> employeeList = new ArrayList<Employee>();
             
            conn = Connect.getConnection();
            String s = "SELECT * FROM employee";
            
            try {
            st = conn.createStatement();
            rs = st.executeQuery(s);
            
            
            while (rs.next()) {
                employee = new Employee(rs.getString("employeeID"), rs.getString("employeeName"), rs.getString("employeeSex"), rs.getString("employeeDOB"), rs.getString("employeePhoneNumber"), rs.getString("employeeAddress"), rs.getString("employeeUserName"));
                employeeList.add(employee);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 1);
            
        }
            return employeeList;
    }
    
    public void showEmployeeInTable() {
        ArrayList<Employee> list = getEmployeeList();
        
        model = (DefaultTableModel) tableInfomationEmployee.getModel();
        
        Object[] row = new Object[7];
        for (int i=0;i<list.size();i++) {
            row[0] = list.get(i).getEmployeeID();
            row[1] = list.get(i).getEmployeeName();
            row[2] = list.get(i).getEmployeeSex();
            row[3] = list.get(i).getEmployeeDOB();
            row[4] = list.get(i).getEmployeePhone();
            row[5] = list.get(i).getEmployeeAddress();
            row[6] = list.get(i).getEmployeeUsername();
            
            model.addRow(row);
        }
    }
    
    public void showEmployee(int index) {
        EmployeeEdit empEdit = new EmployeeEdit();
        
        //set title la ten nhan vien
        empEdit.setTitle(getEmployeeList().get(index).getEmployeeName());
        
        empEdit.textFieldEmployeeName.setText(getEmployeeList().get(index).getEmployeeName());
        empEdit.textFieldEmployeeID.setText(getEmployeeList().get(index).getEmployeeID());
        empEdit.textFieldEmployeeAddress.setText(getEmployeeList().get(index).getEmployeeAddress());
        empEdit.textFieldEmployeePhoneNumber.setText(getEmployeeList().get(index).getEmployeePhone());
        empEdit.textFieldEmployeeUserName.setText(getEmployeeList().get(index).getEmployeeUsername());
        
        try {
        Date date = null;
        date = new SimpleDateFormat("yyyy-MM-dd").parse((String)getEmployeeList().get(index).getEmployeeDOB());
        empEdit.dateChooserEmployeeDOB.setDate(date);
        
        
        empEdit.setVisible(true);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Please choose a employee to edit", "Message", 1); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 1);
            //e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttonAddEmployee = new javax.swing.JLabel();
        buttonEditEmployee = new javax.swing.JLabel();
        buttonDeleteEmployee = new javax.swing.JLabel();
        leftBackgroundEmployeeManage = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        logoEmployeesManage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldSearch = new javax.swing.JTextField();
        separatorSearchEmployee = new javax.swing.JSeparator();
        buttonSearchEmployee = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableInfomationEmployee = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(null);

        buttonAddEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonAddEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Add User Male_48px.png"))); // NOI18N
        buttonAddEmployee.setToolTipText("Add Employee");
        buttonAddEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonAddEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAddEmployeeMouseClicked(evt);
            }
        });
        jPanel2.add(buttonAddEmployee);
        buttonAddEmployee.setBounds(0, 370, 70, 60);

        buttonEditEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonEditEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Edit_48px.png"))); // NOI18N
        buttonEditEmployee.setToolTipText("Edit Employee");
        buttonEditEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEditEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEditEmployeeMouseClicked(evt);
            }
        });
        jPanel2.add(buttonEditEmployee);
        buttonEditEmployee.setBounds(0, 532, 70, 60);

        buttonDeleteEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonDeleteEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Trash Can_48px.png"))); // NOI18N
        buttonDeleteEmployee.setToolTipText("Delete Employee");
        buttonDeleteEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonDeleteEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDeleteEmployeeMouseClicked(evt);
            }
        });
        jPanel2.add(buttonDeleteEmployee);
        buttonDeleteEmployee.setBounds(0, 690, 70, 60);

        leftBackgroundEmployeeManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/031 Blessing.png"))); // NOI18N
        jPanel2.add(leftBackgroundEmployeeManage);
        leftBackgroundEmployeeManage.setBounds(0, 0, 70, 820);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, 0, 70, 60);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);
        jPanel5.setBounds(0, 370, 70, 60);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);
        jPanel6.setBounds(0, 540, 70, 60);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7);
        jPanel7.setBounds(0, 690, 70, 60);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 820));

        jPanel3.setLayout(null);

        logoEmployeesManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/header_logo.png"))); // NOI18N
        jPanel3.add(logoEmployeesManage);
        logoEmployeesManage.setBounds(60, 30, 280, 190);

        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabel4);
        jLabel4.setBounds(1110, 20, 0, 50);

        textFieldSearch.setBackground(new java.awt.Color(229, 238, 206));
        textFieldSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textFieldSearch.setBorder(null);
        textFieldSearch.setOpaque(false);
        jPanel3.add(textFieldSearch);
        textFieldSearch.setBounds(800, 40, 300, 30);
        jPanel3.add(separatorSearchEmployee);
        separatorSearchEmployee.setBounds(800, 72, 310, 10);

        buttonSearchEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Search_48px.png"))); // NOI18N
        buttonSearchEmployee.setToolTipText("Search Employee by name");
        buttonSearchEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSearchEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSearchEmployeeMouseClicked(evt);
            }
        });
        jPanel3.add(buttonSearchEmployee);
        buttonSearchEmployee.setBounds(1110, 20, 60, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/031 Blessing.png"))); // NOI18N
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 0, 1180, 280);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 1200, 280));

        jPanel9.setLayout(null);

        tableInfomationEmployee.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tableInfomationEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Employee Name", "Sex", "DOB", "Phone Number", "Address", "User Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableInfomationEmployee.setGridColor(new java.awt.Color(255, 255, 255));
        tableInfomationEmployee.setRowHeight(20);
        tableInfomationEmployee.setSelectionBackground(new java.awt.Color(233, 235, 197));
        tableInfomationEmployee.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(tableInfomationEmployee);
        if (tableInfomationEmployee.getColumnModel().getColumnCount() > 0) {
            tableInfomationEmployee.getColumnModel().getColumn(0).setResizable(false);
            tableInfomationEmployee.getColumnModel().getColumn(1).setResizable(false);
            tableInfomationEmployee.getColumnModel().getColumn(2).setResizable(false);
            tableInfomationEmployee.getColumnModel().getColumn(3).setResizable(false);
            tableInfomationEmployee.getColumnModel().getColumn(4).setResizable(false);
            tableInfomationEmployee.getColumnModel().getColumn(5).setResizable(false);
            tableInfomationEmployee.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel9.add(jScrollPane2);
        jScrollPane2.setBounds(2, 2, 1180, 540);

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 1180, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddEmployeeMouseClicked
        // TODO add your handling code here:
        EmployeeAdd empAdd = new EmployeeAdd();
        empAdd.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_buttonAddEmployeeMouseClicked

    private void buttonEditEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditEmployeeMouseClicked
        // TODO add your handling code here:
        try {
            int index = tableInfomationEmployee.getSelectedRow();
            showEmployee(index);
            this.dispose();
            } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Please choose a employee to edit", "Message", 1); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 1);
            //e.printStackTrace();
        }
        
    }//GEN-LAST:event_buttonEditEmployeeMouseClicked

    private void buttonDeleteEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDeleteEmployeeMouseClicked
        // TODO add your handling code here:
        try {
                conn = Connect.getConnection();
                st = conn.createStatement();
                
                
                int index = tableInfomationEmployee.getSelectedRow();
                int id = Integer.parseInt(getEmployeeList().get(index).getEmployeeID());
                
                st.executeUpdate(String.format("delete from employee where employeeID=%d", id));
                
                JOptionPane.showMessageDialog(this, "Employee deleted successfully", "Success", 1);
                
                model.setRowCount(0);
                this.showEmployeeInTable();
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Please choose a employee to delete", "Message", 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_buttonDeleteEmployeeMouseClicked

    private void buttonSearchEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSearchEmployeeMouseClicked
        // TODO add your handling code here:
        try {
            String search = textFieldSearch.getText().trim();
            
            //neu o search khong co gi thi load lai bang
        if (textFieldSearch.getText().trim().length() == 0 ) { 
            model.setRowCount(0);
            this.showEmployeeInTable();
        } else {
                conn = Connect.getConnection();
                st = conn.createStatement();
                
                rs = st.executeQuery("select * from employee where employeeName like '%"+search+"%'");
                
                model.setRowCount(0);
                
                while (rs.next()) {
                model.addRow(new Object[]{
                rs.getInt("employeeID"),
                    rs.getString("employeeName"),
                    rs.getString("employeeSex"),
                    rs.getString("employeeDOB"),
                    rs.getString("employeePhoneNumber"),
                    rs.getString("employeeAddress"),
                    rs.getString("employeeUserName")
        });
            }
                
                 
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 1);
            //e.printStackTrace();
        }
    }//GEN-LAST:event_buttonSearchEmployeeMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeManage().setVisible(true);
            }
        });
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonAddEmployee;
    private javax.swing.JLabel buttonDeleteEmployee;
    private javax.swing.JLabel buttonEditEmployee;
    private javax.swing.JLabel buttonSearchEmployee;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel leftBackgroundEmployeeManage;
    private javax.swing.JLabel logoEmployeesManage;
    private javax.swing.JSeparator separatorSearchEmployee;
    private javax.swing.JTable tableInfomationEmployee;
    private javax.swing.JTextField textFieldSearch;
    // End of variables declaration//GEN-END:variables
}
