/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canteen_employees;

/**
 *
 * @author Admin
 */
public class EmployeeDetail extends javax.swing.JFrame {

    /**
     * Creates new form EmployeesDetail
     */
    public EmployeeDetail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelEmployeeID = new javax.swing.JLabel();
        textFieldEmployeeID = new javax.swing.JTextField();
        separatorEmployeeID = new javax.swing.JSeparator();
        labelEmployeeName = new javax.swing.JLabel();
        textFieldEmployeeName = new javax.swing.JTextField();
        separatorEmployeeName = new javax.swing.JSeparator();
        labelEmployeeSex = new javax.swing.JLabel();
        radioButtonMale = new javax.swing.JRadioButton();
        radioButtonFemale = new javax.swing.JRadioButton();
        labelEmployeeDOB = new javax.swing.JLabel();
        separatorEmployeeDOB = new javax.swing.JSeparator();
        labelEmployeePhoneNumber = new javax.swing.JLabel();
        textFieldEmployeePhoneNumber = new javax.swing.JTextField();
        separatorEmployeePhoneNumber = new javax.swing.JSeparator();
        labelEmployeeAddress = new javax.swing.JLabel();
        textFieldEmployeeAddress = new javax.swing.JTextField();
        separatorEmployeeAddress = new javax.swing.JSeparator();
        buttonSave = new keeptoo.KButton();
        buttonCancel = new keeptoo.KButton();
        iconEmployeeDOB = new javax.swing.JLabel();
        iconEmployeeSex = new javax.swing.JLabel();
        iconEmployeeID = new javax.swing.JLabel();
        iconEmployeePhoneNumber = new javax.swing.JLabel();
        iconEmployeeAddress = new javax.swing.JLabel();
        iconEmployeeName = new javax.swing.JLabel();
        dateChooserEmployeeDOB = new com.toedter.calendar.JDateChooser();
        backgroundEmployeeDetail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelEmployeeID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelEmployeeID.setForeground(new java.awt.Color(0, 153, 255));
        labelEmployeeID.setText("Mã Nhân Viên");
        jPanel1.add(labelEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        textFieldEmployeeID.setBackground(new java.awt.Color(226, 239, 211));
        textFieldEmployeeID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textFieldEmployeeID.setBorder(null);
        textFieldEmployeeID.setOpaque(false);
        jPanel1.add(textFieldEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 250, 30));
        jPanel1.add(separatorEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 250, 10));

        labelEmployeeName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelEmployeeName.setForeground(new java.awt.Color(0, 153, 255));
        labelEmployeeName.setText("Tên Nhân Viên");
        jPanel1.add(labelEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        textFieldEmployeeName.setBackground(new java.awt.Color(229, 237, 204));
        textFieldEmployeeName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textFieldEmployeeName.setBorder(null);
        textFieldEmployeeName.setOpaque(false);
        textFieldEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmployeeNameActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 250, 30));
        jPanel1.add(separatorEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 250, 10));

        labelEmployeeSex.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelEmployeeSex.setForeground(new java.awt.Color(0, 153, 255));
        labelEmployeeSex.setText("Giới Tính");
        jPanel1.add(labelEmployeeSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        radioButtonMale.setBackground(new java.awt.Color(232, 235, 197));
        radioButtonMale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioButtonMale.setText("Nam");
        jPanel1.add(radioButtonMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        radioButtonFemale.setBackground(new java.awt.Color(232, 235, 197));
        radioButtonFemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioButtonFemale.setText("Nữ");
        jPanel1.add(radioButtonFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        labelEmployeeDOB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelEmployeeDOB.setForeground(new java.awt.Color(0, 153, 255));
        labelEmployeeDOB.setText("Ngày Sinh");
        jPanel1.add(labelEmployeeDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));
        jPanel1.add(separatorEmployeeDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 240, 10));

        labelEmployeePhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelEmployeePhoneNumber.setForeground(new java.awt.Color(0, 153, 255));
        labelEmployeePhoneNumber.setText("Số Điện Thoại");
        jPanel1.add(labelEmployeePhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        textFieldEmployeePhoneNumber.setBackground(new java.awt.Color(229, 237, 204));
        textFieldEmployeePhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textFieldEmployeePhoneNumber.setBorder(null);
        textFieldEmployeePhoneNumber.setOpaque(false);
        jPanel1.add(textFieldEmployeePhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 240, 30));
        jPanel1.add(separatorEmployeePhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 240, 20));

        labelEmployeeAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelEmployeeAddress.setForeground(new java.awt.Color(0, 153, 255));
        labelEmployeeAddress.setText("Địa Chỉ");
        jPanel1.add(labelEmployeeAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        textFieldEmployeeAddress.setBackground(new java.awt.Color(232, 236, 199));
        textFieldEmployeeAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textFieldEmployeeAddress.setBorder(null);
        textFieldEmployeeAddress.setOpaque(false);
        jPanel1.add(textFieldEmployeeAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 240, 30));
        jPanel1.add(separatorEmployeeAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 240, 10));

        buttonSave.setText("Lưu");
        buttonSave.setkBackGroundColor(new java.awt.Color(0, 204, 102));
        buttonSave.setkBorderRadius(50);
        buttonSave.setkEndColor(new java.awt.Color(102, 255, 153));
        buttonSave.setkForeGround(new java.awt.Color(0, 0, 0));
        buttonSave.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        buttonSave.setkHoverStartColor(new java.awt.Color(0, 153, 102));
        jPanel1.add(buttonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        buttonCancel.setText("Thoát");
        buttonCancel.setkBackGroundColor(new java.awt.Color(0, 204, 102));
        buttonCancel.setkBorderRadius(50);
        buttonCancel.setkEndColor(new java.awt.Color(102, 255, 153));
        buttonCancel.setkForeGround(new java.awt.Color(0, 0, 0));
        buttonCancel.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        buttonCancel.setkHoverStartColor(new java.awt.Color(0, 153, 102));
        jPanel1.add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, -1, -1));

        iconEmployeeDOB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Calendar_32px.png"))); // NOI18N
        jPanel1.add(iconEmployeeDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 40, 30));

        iconEmployeeSex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Gender_32px.png"))); // NOI18N
        jPanel1.add(iconEmployeeSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 40, 30));

        iconEmployeeID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Identification Documents_32px.png"))); // NOI18N
        jPanel1.add(iconEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 40, 30));

        iconEmployeePhoneNumber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Number Pad_32px.png"))); // NOI18N
        jPanel1.add(iconEmployeePhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 40, 30));

        iconEmployeeAddress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Marker_32px.png"))); // NOI18N
        jPanel1.add(iconEmployeeAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 40, 30));

        iconEmployeeName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/User Male_32px.png"))); // NOI18N
        jPanel1.add(iconEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 40, 30));

        dateChooserEmployeeDOB.setOpaque(false);
        jPanel1.add(dateChooserEmployeeDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 220, 30));

        backgroundEmployeeDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/031 Blessing.png"))); // NOI18N
        jPanel1.add(backgroundEmployeeDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmployeeNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundEmployeeDetail;
    private keeptoo.KButton buttonCancel;
    private keeptoo.KButton buttonSave;
    private com.toedter.calendar.JDateChooser dateChooserEmployeeDOB;
    private javax.swing.JLabel iconEmployeeAddress;
    private javax.swing.JLabel iconEmployeeDOB;
    private javax.swing.JLabel iconEmployeeID;
    private javax.swing.JLabel iconEmployeeName;
    private javax.swing.JLabel iconEmployeePhoneNumber;
    private javax.swing.JLabel iconEmployeeSex;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelEmployeeAddress;
    private javax.swing.JLabel labelEmployeeDOB;
    private javax.swing.JLabel labelEmployeeID;
    private javax.swing.JLabel labelEmployeeName;
    private javax.swing.JLabel labelEmployeePhoneNumber;
    private javax.swing.JLabel labelEmployeeSex;
    private javax.swing.JRadioButton radioButtonFemale;
    private javax.swing.JRadioButton radioButtonMale;
    private javax.swing.JSeparator separatorEmployeeAddress;
    private javax.swing.JSeparator separatorEmployeeDOB;
    private javax.swing.JSeparator separatorEmployeeID;
    private javax.swing.JSeparator separatorEmployeeName;
    private javax.swing.JSeparator separatorEmployeePhoneNumber;
    private javax.swing.JTextField textFieldEmployeeAddress;
    private javax.swing.JTextField textFieldEmployeeID;
    private javax.swing.JTextField textFieldEmployeeName;
    private javax.swing.JTextField textFieldEmployeePhoneNumber;
    // End of variables declaration//GEN-END:variables
}
