/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canteen_main;

import canteen_login.LoginAdmin;
import javafx.scene.paint.Color;
import javax.swing.JPanel;
import canteen_login.LoginEmployee;
import canteen_products.ProductManage;
import canteen_register.registerAdmin;

/**
 *
 * @author My Computer
 */
public class AdminMain extends javax.swing.JFrame {

    /**
     * Creates new form Trangchu
     */
    public AdminMain() {
        initComponents();
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bigLogo = new javax.swing.JLabel();
        logoBackground = new javax.swing.JLabel();
        mainMenu = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelLogout = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelManage = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelBill = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelAnalyze = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelAddAdmin = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        menuBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(null);

        bigLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/banner.png"))); // NOI18N
        jPanel2.add(bigLogo);
        bigLogo.setBounds(220, 20, 840, 210);

        logoBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/034 Lemon Gate.png"))); // NOI18N
        jPanel2.add(logoBackground);
        logoBackground.setBounds(1, 0, 1360, 250);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 250));

        mainMenu.setBackground(new java.awt.Color(255, 255, 255));
        mainMenu.setLayout(null);

        panelMenu.setBackground(new java.awt.Color(153, 255, 153));
        panelMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMenuMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Food_96px.png"))); // NOI18N
        jLabel1.setText("Thực Đơn");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        mainMenu.add(panelMenu);
        panelMenu.setBounds(70, 30, 240, 170);

        panelLogout.setBackground(new java.awt.Color(153, 255, 153));
        panelLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLogoutMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Logout Rounded Left_96px.png"))); // NOI18N
        jLabel4.setText("Đăng Xuất");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelLogoutLayout = new javax.swing.GroupLayout(panelLogout);
        panelLogout.setLayout(panelLogoutLayout);
        panelLogoutLayout.setHorizontalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoutLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel4)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        panelLogoutLayout.setVerticalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        mainMenu.add(panelLogout);
        panelLogout.setBounds(1040, 250, 240, 170);

        panelManage.setBackground(new java.awt.Color(153, 255, 153));
        panelManage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelManage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelManageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelManageMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Manager_100px.png"))); // NOI18N
        jLabel5.setText("Nhân Viên");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelManageLayout = new javax.swing.GroupLayout(panelManage);
        panelManage.setLayout(panelManageLayout);
        panelManageLayout.setHorizontalGroup(
            panelManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelManageLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(66, 66, 66))
        );
        panelManageLayout.setVerticalGroup(
            panelManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        mainMenu.add(panelManage);
        panelManage.setBounds(560, 30, 240, 170);

        panelBill.setBackground(new java.awt.Color(153, 255, 153));
        panelBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBillMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBillMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBillMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Purchase Order_96px.png"))); // NOI18N
        jLabel2.setText("Hóa Đơn");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelBillLayout = new javax.swing.GroupLayout(panelBill);
        panelBill.setLayout(panelBillLayout);
        panelBillLayout.setHorizontalGroup(
            panelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBillLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(63, 63, 63))
        );
        panelBillLayout.setVerticalGroup(
            panelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        mainMenu.add(panelBill);
        panelBill.setBounds(1040, 30, 240, 170);

        panelAnalyze.setBackground(new java.awt.Color(153, 255, 153));
        panelAnalyze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelAnalyze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAnalyzeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAnalyzeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAnalyzeMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Increase_100px.png"))); // NOI18N
        jLabel7.setText("Thống Kê");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelAnalyzeLayout = new javax.swing.GroupLayout(panelAnalyze);
        panelAnalyze.setLayout(panelAnalyzeLayout);
        panelAnalyzeLayout.setHorizontalGroup(
            panelAnalyzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnalyzeLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel7)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        panelAnalyzeLayout.setVerticalGroup(
            panelAnalyzeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnalyzeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        mainMenu.add(panelAnalyze);
        panelAnalyze.setBounds(70, 250, 240, 170);

        panelAddAdmin.setBackground(new java.awt.Color(153, 255, 153));
        panelAddAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelAddAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAddAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAddAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAddAdminMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Plus_100px.png"))); // NOI18N
        jLabel6.setText("Thêm Admin");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelAddAdminLayout = new javax.swing.GroupLayout(panelAddAdmin);
        panelAddAdmin.setLayout(panelAddAdminLayout);
        panelAddAdminLayout.setHorizontalGroup(
            panelAddAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddAdminLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(46, 46, 46))
        );
        panelAddAdminLayout.setVerticalGroup(
            panelAddAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        mainMenu.add(panelAddAdmin);
        panelAddAdmin.setBounds(560, 250, 240, 170);

        menuBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/034 Lemon Gate.png"))); // NOI18N
        mainMenu.add(menuBackground);
        menuBackground.setBounds(0, 0, 1360, 440);

        jPanel1.add(mainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1360, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuMouseEntered
        // TODO add your handling code here:
        setColorMouseEntered(panelMenu);
    }//GEN-LAST:event_panelMenuMouseEntered

    private void panelMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuMouseExited
        // TODO add your handling code here:
        resetColor((panelMenu));
    }//GEN-LAST:event_panelMenuMouseExited

    private void panelBillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBillMouseEntered
        // TODO add your handling code here:
        setColorMouseEntered(panelBill);
    }//GEN-LAST:event_panelBillMouseEntered

    private void panelBillMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBillMouseExited
        // TODO add your handling code here:
        resetColor(panelBill);
    }//GEN-LAST:event_panelBillMouseExited

    private void panelLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseEntered
        // TODO add your handling code here:
        setColorMouseEntered(panelLogout);
    }//GEN-LAST:event_panelLogoutMouseEntered

    private void panelLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseExited
        // TODO add your handling code here:
        resetColor(panelLogout);
    }//GEN-LAST:event_panelLogoutMouseExited

    private void panelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuMouseClicked
        // TODO add your handling code here:
        setColorMouseClicked(panelMenu);
        ProductManage prodMng = new ProductManage();
        prodMng.setVisible(true);
        
    }//GEN-LAST:event_panelMenuMouseClicked

    private void panelBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBillMouseClicked
        // TODO add your handling code here:
        setColorMouseClicked(panelBill);
    }//GEN-LAST:event_panelBillMouseClicked

    private void panelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseClicked
        // TODO add your handling code here:
        setColorMouseClicked(panelLogout);
        
        this.dispose();
        LoginAdmin logAd = new LoginAdmin();
        logAd.setVisible(true);
    }//GEN-LAST:event_panelLogoutMouseClicked

    private void panelManageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageMouseClicked
        // TODO add your handling code here:
        setColorMouseClicked(panelManage);
    }//GEN-LAST:event_panelManageMouseClicked

    private void panelManageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageMouseEntered
        // TODO add your handling code here:
        setColorMouseEntered(panelManage);
    }//GEN-LAST:event_panelManageMouseEntered

    private void panelManageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageMouseExited
        // TODO add your handling code here:
        resetColor(panelManage);
    }//GEN-LAST:event_panelManageMouseExited

    private void panelAddAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddAdminMouseClicked
        // TODO add your handling code here:
        setColorMouseClicked(panelAddAdmin);
        
        registerAdmin regAd = new registerAdmin();
        regAd.setVisible(true);
    }//GEN-LAST:event_panelAddAdminMouseClicked

    private void panelAddAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddAdminMouseEntered
        // TODO add your handling code here:
        setColorMouseEntered(panelAddAdmin);
    }//GEN-LAST:event_panelAddAdminMouseEntered

    private void panelAddAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddAdminMouseExited
        // TODO add your handling code here:
        resetColor(panelAddAdmin);
    }//GEN-LAST:event_panelAddAdminMouseExited

    private void panelAnalyzeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAnalyzeMouseClicked
        // TODO add your handling code here:
        setColorMouseClicked(panelAnalyze);
    }//GEN-LAST:event_panelAnalyzeMouseClicked

    private void panelAnalyzeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAnalyzeMouseEntered
        // TODO add your handling code here:
        setColorMouseEntered(panelAnalyze);
    }//GEN-LAST:event_panelAnalyzeMouseEntered

    private void panelAnalyzeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAnalyzeMouseExited
        // TODO add your handling code here:
        resetColor(panelAnalyze);
    }//GEN-LAST:event_panelAnalyzeMouseExited
public void setColorMouseEntered(JPanel panel){
    panel.setBackground(new java.awt.Color(51, 255, 153));
}

public void resetColor(JPanel panel){
    panel.setBackground(new java.awt.Color(153,255,153));
}

public void setColorMouseClicked(JPanel panel){
    panel.setBackground(new java.awt.Color(0,204,102));
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bigLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logoBackground;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JLabel menuBackground;
    private javax.swing.JPanel panelAddAdmin;
    private javax.swing.JPanel panelAnalyze;
    private javax.swing.JPanel panelBill;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelManage;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}

