/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canteen_products;

import canteen_connection.Connect;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ProductManage extends javax.swing.JFrame {
    
    Product product;
    DefaultTableModel model;
    Connection conn;
    Statement st;
    ResultSet rs;
    
    /**
     * Creates new form NewJFrame
     */
    public ProductManage() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
//        loadTable();
        showProductInTable();
    }
    
    public ArrayList<Product> getProductList() {
        
            ArrayList<Product> productList = new ArrayList<Product>();
             
            conn = Connect.getConnection();
            String s = "SELECT * FROM productmenu LEFT JOIN producttype on productmenu.productTypeID = producttype.productTypeID";
            
            try {
            st = conn.createStatement();
            rs = st.executeQuery(s);
            
            
            while (rs.next()) {
                product = new Product(rs.getString("productID"), rs.getString("productName"), rs.getString("productType"), rs.getString("price"));
                productList.add(product);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 1);
        }
            return productList;
    }

    public void showProductInTable() {
        ArrayList<Product> list = getProductList();
        
        model = (DefaultTableModel) tableProductMenu.getModel();
        
        Object[] row = new Object[4];
        for (int i=0;i<list.size();i++) {
            row[0] = list.get(i).getProductID();
            row[1] = list.get(i).getProductName();
            row[2] = list.get(i).getProductTypeID();
            row[3] = list.get(i).getPrice();
            
            model.addRow(row);
        }
    }
    
    public void showItem(int index) {
        ProductEdit prodEdit = new ProductEdit();
        
        prodEdit.setTitle(getProductList().get(index).getProductName());
        prodEdit.textfieldProductID.setText(getProductList().get(index).getProductID());
        prodEdit.textfieldProductName.setText(getProductList().get(index).getProductName());
        prodEdit.comboBoxProductType.setSelectedItem(getProductList().get(index).getProductTypeID());
        prodEdit.textfieldProductPrice.setText(getProductList().get(index).getPrice());
        
        prodEdit.setVisible(true);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        buttonAdd = new javax.swing.JLabel();
        buttonEdit = new javax.swing.JLabel();
        buttonDelete = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        logo = new javax.swing.JLabel();
        buttonSearch = new javax.swing.JLabel();
        textFieldSearch = new javax.swing.JTextField();
        separatorSearch = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductMenu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mặt hàng");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(153, 255, 153));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setLayout(null);

        buttonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Add_50px.png"))); // NOI18N
        buttonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAddMouseClicked(evt);
            }
        });
        kGradientPanel1.add(buttonAdd);
        buttonAdd.setBounds(10, 370, 50, 50);

        buttonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Edit_48px.png"))); // NOI18N
        buttonEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEditMouseClicked(evt);
            }
        });
        kGradientPanel1.add(buttonEdit);
        buttonEdit.setBounds(10, 550, 50, 40);

        buttonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Trash Can_48px.png"))); // NOI18N
        buttonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDeleteMouseClicked(evt);
            }
        });
        kGradientPanel1.add(buttonDelete);
        buttonDelete.setBounds(10, 714, 50, 40);

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 820));

        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(153, 255, 153));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel2.setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/header_logo.png"))); // NOI18N
        kGradientPanel2.add(logo);
        logo.setBounds(40, 30, 270, 190);

        buttonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canteen_image/Search_48px.png"))); // NOI18N
        buttonSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel2.add(buttonSearch);
        buttonSearch.setBounds(1090, 28, 48, 50);

        textFieldSearch.setBackground(new java.awt.Color(153, 255, 153));
        textFieldSearch.setBorder(null);
        kGradientPanel2.add(textFieldSearch);
        textFieldSearch.setBounds(790, 40, 300, 30);
        kGradientPanel2.add(separatorSearch);
        separatorSearch.setBounds(790, 80, 300, 10);

        jPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 1180, -1));

        tableProductMenu.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tableProductMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ProductName", "ProductType", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProductMenu.setEditingColumn(0);
        tableProductMenu.setEditingRow(0);
        tableProductMenu.setGridColor(new java.awt.Color(255, 255, 255));
        tableProductMenu.setSelectionBackground(new java.awt.Color(233, 235, 197));
        tableProductMenu.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(tableProductMenu);
        if (tableProductMenu.getColumnModel().getColumnCount() > 0) {
            tableProductMenu.getColumnModel().getColumn(0).setResizable(false);
            tableProductMenu.getColumnModel().getColumn(1).setResizable(false);
            tableProductMenu.getColumnModel().getColumn(2).setResizable(false);
            tableProductMenu.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 1180, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseClicked
        // TODO add your handling code here:
        ProductAdd prodAdd = new ProductAdd();
        prodAdd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAddMouseClicked

    private void buttonEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditMouseClicked
        // TODO add your handling code here:
        
        try {
            int index = tableProductMenu.getSelectedRow();
            showItem(index);
            this.dispose();
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Please choose a product to edit", "Message", 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 1);
        }
        
    }//GEN-LAST:event_buttonEditMouseClicked

    private void buttonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDeleteMouseClicked
        // TODO add your handling code here:
        try {
                conn = Connect.getConnection();
                st = conn.createStatement();
                
                
                int index = tableProductMenu.getSelectedRow();
                int id = Integer.parseInt(getProductList().get(index).getProductID());
                
                st.executeUpdate(String.format("delete from productMenu where productID=%d", id));
                
                JOptionPane.showMessageDialog(this, "Product deleted successfully", "Success", 1);
                
                model.setRowCount(0);
                this.showProductInTable();
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Please choose a product to delete", "Message", 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 1);
        }
    }//GEN-LAST:event_buttonDeleteMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductManage().setVisible(true);
            }
        });
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonAdd;
    private javax.swing.JLabel buttonDelete;
    private javax.swing.JLabel buttonEdit;
    private javax.swing.JLabel buttonSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JSeparator separatorSearch;
    private javax.swing.JTable tableProductMenu;
    private javax.swing.JTextField textFieldSearch;
    // End of variables declaration//GEN-END:variables
}
